working

diff --git a/.yadm/bootstrap b/.yadm/bootstrap
--- a/.yadm/bootstrap
+++ b/.yadm/bootstrap
@@ -2,9 +2,9 @@
 # vim: set foldmethod=marker ft=sh:
 
 # helper functions {{{
-function log_info() { echo -e "$(tput setaf 2)$(tput rev)$(tput bold) \xE2\x9C\x93 $1 $(tput sgr0)"; }
-function log_error() { echo -e "$(tput setaf 1)$(tput rev)$(tput bold) \xE2\x9C\x97 $1 $(tput sgr0)"; }
-function log_notice() { echo -e "$(tput setaf 3)$(tput rev)$(tput bold) \xE2\x9A\xa0 $1 $(tput sgr0)"; }
+function log_info() { echo -e "$(tput setaf 2)$(tput rev)$(tput bold) \xE2\x9C\x93 $1 $(tput sgr0)"; ${@:2}; }
+function log_error() { echo -e "$(tput setaf 1)$(tput rev)$(tput bold) \xE2\x9C\x97 $1 $(tput sgr0)"; ${@:2}; }
+function log_notice() { echo -e "$(tput setaf 3)$(tput rev)$(tput bold) \xE2\x9A\xa0 $1 $(tput sgr0)"; ${@:2}; }
 # }}}
 
 # clone repos {{{
@@ -16,22 +16,22 @@ cd "$HOME/Code"
 cd -
 
 # saatchi repos {{{
-mkdir -p "$HOME/Code/saatchi"
-cd "$HOME/Code/saatchi"
-[[ -d "$HOME/Code/saatchi/api" ]] || git clone git@github.com:saatchiart/api.git
-[[ -d "$HOME/Code/saatchi/catalog" ]] || git clone git@github.com:saatchiart/catalog.git
-[[ -d "$HOME/Code/saatchi/couchbase-views" ]] || git clone git@github.com:saatchiart/couchbase-views.git
-[[ -d "$HOME/Code/saatchi/easel" ]] || git clone git@github.com:saatchiart/easel.git
-[[ -d "$HOME/Code/saatchi/gallery" ]] || git clone git@github.com:saatchiart/gallery.git
-[[ -d "$HOME/Code/saatchi/gitlab-puppet" ]] || git clone ab.dmdmedia.net:mike.funk/saatchi.git
-[[ -d "$HOME/Code/saatchi/imgproc" ]] || git clone git@github.com:saatchiart/imgproc.git
-[[ -d "$HOME/Code/saatchi/maropost-php-sdk" ]] || git clone git@github.com:saatchiart/maropost-php-sdk.git
-[[ -d "$HOME/Code/saatchi/palette" ]] || git clone git@github.com:saatchiart/palette.git
-[[ -d "$HOME/Code/saatchi/potato" ]] || git clone git@github.com:saatchiart/potato.git
-[[ -d "$HOME/Code/saatchi/saatchiart" ]] || git clone git@github.com:saatchiart/saatchiart.git
-[[ -d "$HOME/Code/saatchi/xdocker" ]] || git clone git@github.com:saatchiart/xdocker.git
-[[ -d "$HOME/Code/saatchi/yzed" ]] || git clone git@github.com:saatchiart/yzed.git
-cd -
+# mkdir -p "$HOME/Code/saatchi"
+# cd "$HOME/Code/saatchi"
+# [[ -d "$HOME/Code/saatchi/api" ]] || git clone git@github.com:saatchiart/api.git
+# [[ -d "$HOME/Code/saatchi/catalog" ]] || git clone git@github.com:saatchiart/catalog.git
+# [[ -d "$HOME/Code/saatchi/couchbase-views" ]] || git clone git@github.com:saatchiart/couchbase-views.git
+# [[ -d "$HOME/Code/saatchi/easel" ]] || git clone git@github.com:saatchiart/easel.git
+# [[ -d "$HOME/Code/saatchi/gallery" ]] || git clone git@github.com:saatchiart/gallery.git
+# [[ -d "$HOME/Code/saatchi/gitlab-puppet" ]] || git clone ab.dmdmedia.net:mike.funk/saatchi.git
+# [[ -d "$HOME/Code/saatchi/imgproc" ]] || git clone git@github.com:saatchiart/imgproc.git
+# [[ -d "$HOME/Code/saatchi/maropost-php-sdk" ]] || git clone git@github.com:saatchiart/maropost-php-sdk.git
+# [[ -d "$HOME/Code/saatchi/palette" ]] || git clone git@github.com:saatchiart/palette.git
+# [[ -d "$HOME/Code/saatchi/potato" ]] || git clone git@github.com:saatchiart/potato.git
+# [[ -d "$HOME/Code/saatchi/saatchiart" ]] || git clone git@github.com:saatchiart/saatchiart.git
+# [[ -d "$HOME/Code/saatchi/xdocker" ]] || git clone git@github.com:saatchiart/xdocker.git
+# [[ -d "$HOME/Code/saatchi/yzed" ]] || git clone git@github.com:saatchiart/yzed.git
+# cd -
 # }}}
 
 # }}}
@@ -97,24 +97,18 @@ fi
 # phpenv {{{
 # I only use this because homebrew is making it difficult to install php 7.0
 # and extensions right now.
-if [[ ! "$(builtin type -p phpenv)" ]]; then
-	log_info "Installing phpenv"
-	# curl -L http://git.io/phpenv-installer | bash
-else
-	log_info "Updating phpenv"
-	# this breaks all of the sed replacements to turn rbenv into phpenv :/
-	# phpenv update
-	# to uninstall: rm -rf $(phpenv root)
-fi
+#
+# Update 11-16-2018: php 7.0 is still not on homebrew. I looked into asdf
+# instead but the php plugin is in very shoddy condition. You have to install
+# about 10 brew packages, set several env vars, and add to path before
+# building. And it doesn't handle php extensions.
+log_info "Installing/updating phpenv"
 curl -L http://git.io/phpenv-installer | bash
 # }}}
 
 # update yarn {{{
 log_info "Installing/upgrading yarn packages"
-cd $HOME
-# yarn global install
-yarn global upgrade
-cd -
+cd && yarn global upgrade && cd -
 # }}}
 
 # set zsh as shell {{{
@@ -123,8 +117,7 @@ if [[ $(grep "/usr/local/bin/zsh" /etc/shells -c) == 0 ]]; then
 	sudo /bin/sh -c "echo /usr/local/bin/zsh >> /etc/shells"
 fi
 if [[ "$SHELL" != "/usr/local/bin/zsh" ]]; then
-	log_info "Changing shell to homebrew zsh"
-	chsh -s $(which zsh)
+	log_info "Changing shell to homebrew zsh" chsh -s $(which zsh)
 fi
 # }}}
 
@@ -206,19 +199,6 @@ if [[ ! "$(phpenv versions | grep 7.0.29)" ]]; then
 	# $HOME/.phpenv/pear/bin/pecl install mongodb && ( echo 'extension="mongodb.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/mongodb.ini )
 	# $HOME/.phpenv/pear/bin/pecl install xdebug && ( echo 'zend_extension="xdebug.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/xdebug.ini )
 fi
-
-if [[ ! "$(phpenv versions | grep 7.2.4)" ]]; then
-	log_info "Installing php 7.2.4"
-	phpenv install 7.2.4 && phpenv rehash
-	# phpenv install 7.2.4 && php global 7.2.4 && phpenv rehash
-
-	# install pear so we can use pecl to install extensions
-	# TODO do this in a way where each php version has its own pear :/
-	# log_info "Installing pear"
-	# [ -f "$HOME/.phpenv/bin/go-pear.phar" ] || wget -O "$HOME/.phpenv/bin/go-pear.phar" http://pear.php.net/go-pear.phar
-	# cd $HOME && ./.support/install-pear.sh && cd -
-	# [ -f "$HOME/.phpenv/bin/go-pear.phar" ] && rm "$HOME/.phpenv/bin/go-pear.phar"
-fi
 # }}}
 
 # install ruby version {{{
@@ -250,7 +230,7 @@ fi
 # Installs from ~/Gemfile
 log_info "Installing/upgrading ruby gems"
 gem install bundler
-cd $HOME
+cd
 bundle install --system --binstubs
 bundle clean --force
 cd -
@@ -273,22 +253,25 @@ pip freeze >"$HOME/requirements.txt"
 
 # install/update composer and packages {{{
 # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
+function _install-composer () {
+    EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+    ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
+        echo >&2 'ERROR: Invalid installer signature'
+        rm composer-setup.php
+        exit 1
+    fi
+
+    php composer-setup.php --quiet
+    RESULT=$?
+    rm composer-setup.php
+    exit $RESULT
+}
 if [[ ! "$(builtin type -p composer)" ]]; then
 	log_info "Installing composer"
-	EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
-	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-	ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
-
-	if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
-		echo >&2 'ERROR: Invalid installer signature'
-		rm composer-setup.php
-		exit 1
-	fi
-
-	php composer-setup.php --quiet
-	RESULT=$?
-	rm composer-setup.php
-	exit $RESULT
+    _install-composer
 fi
 log_info "Installing/upgrading composer packages"
 composer global selfupdate
@@ -409,6 +392,6 @@ fi
 
 # reminders {{{
 # log_info "Don't forget to upgrade your docker-machine once in a while!"
-log_info "Don't forget to ''brew cask upgrade virtualbox virtualbox-extension-pack' once in a while!"
+# log_info "Don't forget to ''brew cask upgrade virtualbox virtualbox-extension-pack' once in a while!"
 log_info "Don't forget to update tmux plugins via <c-a>U once in a while!"
 # }}}
