working

diff --git a/.yadm/bootstrap b/.yadm/bootstrap
--- a/.yadm/bootstrap
+++ b/.yadm/bootstrap
@@ -14,19 +14,19 @@ function log_notice() { echo -e "$(tput setaf 3)$(tput rev)$(tput bold) \xE2\x9A
 
 # install homebrew if it's missing {{{
 if ! command -v brew >/dev/null 2>&1; then
-    log_info "Installing homebrew"
-    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+	log_info "Installing homebrew"
+	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 fi
 # }}}
 
 # install/update homebrew packages {{{
 if [ -e "$HOME/.Brewfile" ]; then
-    log_info "Installing/upgrading homebrew packages"
-    brew prune # Remove dead symlinks from the homebrew prefix
-    brew bundle --global # install/upgrade from ~/.Brewfile
-    brew upgrade # upgrade all homebrew packages
-    brew cleanup # remove outdated versions
-    # brew bundle --global cleanup --force # remove brew packages not in ~/.Brewfile
+	log_info "Installing/upgrading homebrew packages"
+	brew prune           # Remove dead symlinks from the homebrew prefix
+	brew bundle --global # install/upgrade from ~/.Brewfile
+	brew upgrade         # upgrade all homebrew packages
+	brew cleanup         # remove outdated versions
+	# brew bundle --global cleanup --force # remove brew packages not in ~/.Brewfile
 fi
 # }}}
 
@@ -34,13 +34,13 @@ fi
 # I only use this because homebrew is making it difficult to install php 7.0
 # and extensions right now.
 if [[ ! "$(builtin type -p phpenv)" ]]; then
-    log_info "Installing phpenv"
-    # curl -L http://git.io/phpenv-installer | bash
+	log_info "Installing phpenv"
+	# curl -L http://git.io/phpenv-installer | bash
 else
-    log_info "Updating phpenv"
-    # this breaks all of the sed replacements to turn rbenv into phpenv :/
-    # phpenv update
-    # to uninstall: rm -rf $(phpenv root)
+	log_info "Updating phpenv"
+	# this breaks all of the sed replacements to turn rbenv into phpenv :/
+	# phpenv update
+	# to uninstall: rm -rf $(phpenv root)
 fi
 curl -L http://git.io/phpenv-installer | bash
 # }}}
@@ -55,19 +55,19 @@ cd -
 
 # set zsh as shell {{{
 if [[ $(grep "/usr/local/bin/zsh" /etc/shells -c) == 0 ]]; then
-    log_info "Installing homebrew zsh to /etc/shells"
-    sudo /bin/sh -c "echo /usr/local/bin/zsh >> /etc/shells"
+	log_info "Installing homebrew zsh to /etc/shells"
+	sudo /bin/sh -c "echo /usr/local/bin/zsh >> /etc/shells"
 fi
 if [[ "$SHELL" != "/usr/local/bin/zsh" ]]; then
-    log_info "Changing shell to homebrew zsh"
-    chsh -s `which zsh`
+	log_info "Changing shell to homebrew zsh"
+	chsh -s $(which zsh)
 fi
 # }}}
 
 # install tmux plugin manager {{{
 if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
-    log_info "Installing tmux plugin manager. Upgrade packages with \`<c-a>U\`."
-    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+	log_info "Installing tmux plugin manager. Upgrade packages with \`<c-a>U\`."
+	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
 fi
 # }}}
 
@@ -75,23 +75,23 @@ fi
 
 # {{{ Directories
 if [[ ! -d "$HOME/.vim/autoload" ]]; then
-    log_info "Creating required vim autoload directory"
-    mkdir -p "$HOME/.vim/autoload" && \
-        chmod +w "$HOME/.vim/autoload"
+	log_info "Creating required vim autoload directory"
+	mkdir -p "$HOME/.vim/autoload" &&
+		chmod +w "$HOME/.vim/autoload"
 fi
 if [[ ! -d "$HOME/.vim/files/info" ]]; then
-    log_info "Creating required vim info directory"
-    mkdir -p "$HOME/.vim/files/info" && \
-    chmod a+w "$HOME/.vim/files/info"
+	log_info "Creating required vim info directory"
+	mkdir -p "$HOME/.vim/files/info" &&
+		chmod a+w "$HOME/.vim/files/info"
 fi
 # }}}
 
 # install vim-plug {{{
 if [[ ! -f $HOME/.vim/autoload/plug.vim ]]; then
-    log_info "Installing vim-plug"
-    curl -fLo \
-        ~/.vim/autoload/plug.vim \
-        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+	log_info "Installing vim-plug"
+	curl -fLo \
+		~/.vim/autoload/plug.vim \
+		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
 fi
 # }}}
 
@@ -105,8 +105,8 @@ vim +PlugInstall +PlugUpdate +PlugClean! +qall
 
 # install node version {{{
 if [[ ! "$(nodenv version | grep 9.3.0)" ]]; then
-    log_info "Installing node 9.3.0"
-    nodenv install 9.3.0 && nodenv rehash && nodenv global 9.3.0
+	log_info "Installing node 9.3.0"
+	nodenv install 9.3.0 && nodenv rehash && nodenv global 9.3.0
 fi
 # }}}
 
@@ -114,64 +114,68 @@ fi
 # I only use phpenv because homebrew is making it difficult to install php 7.0
 # and extensions right now.
 if [[ ! "$(phpenv versions | grep 7.0.29)" ]]; then
-    log_info "Installing php 7.0.29"
-    phpenv install 7.0.29 && phpenv rehash
-    # phpenv install 7.0.29 && php global 7.0.29 && phpenv rehash
+	log_info "Installing php 7.0.29"
+	# phpenv install 7.0.29 && phpenv rehash
 
-    # install pear so we can use pecl to install extensions
-    # TODO do this in a way where each php version has its own pear :/
-    log_info "Installing pear"
-    [ -f "$HOME/.phpenv/bin/go-pear.phar" ] || wget -O "$HOME/.phpenv/bin/go-pear.phar" http://pear.php.net/go-pear.phar
-    cd $HOME && ./.support/install-pear.sh && cd -
-    [ -f "$HOME/.phpenv/bin/go-pear.phar" ] && rm "$HOME/.phpenv/bin/go-pear.phar"
+	# NOTE if I set php 7.1+.x to global and I use directory-specific php
+	# versions and I install global composer dependencies then they will fail
+	# when I have php 7.0.29 active!
+	phpenv install 7.0.29 && php global 7.0.29 && phpenv rehash
 
-    log_info "Installing php extensions"
-    $HOME/.phpenv/pear/bin/pecl install igbinary && ( echo 'extension="igbinary.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/igbinary.ini ) # needed for couchbase
-    $HOME/.phpenv/pear/bin/pecl install couchbase-2.2.2 && ( echo 'extension="couchbase.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/couchbase.ini ) # their sdk has breaking changes all the time
-    # $HOME/.phpenv/pear/bin/pecl install pcntl && ( echo 'zend_extension="pcntl.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/pcntl.ini )
-    # $HOME/.phpenv/pear/bin/pecl install intl && ( echo 'zend_extension="intl.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/intl.ini ) # needed for phpstan build
-    # $HOME/.phpenv/pear/bin/pecl install memcache && ( echo 'zend_extension="memcache.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/memcache.ini ) # needed for zed
-    $HOME/.phpenv/pear/bin/pecl install memcached && ( echo 'extension="memcached.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/memcached.ini )
-    # $HOME/.phpenv/pear/bin/pecl install mongodb && ( echo 'extension="mongodb.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/mongodb.ini )
-    # $HOME/.phpenv/pear/bin/pecl install xdebug && ( echo 'zend_extension="xdebug.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/xdebug.ini )
+	# install pear so we can use pecl to install extensions
+	# TODO do this in a way where each php version has its own pear :/
+	log_info "Installing pear"
+	[ -f "$HOME/.phpenv/bin/go-pear.phar" ] || wget -O "$HOME/.phpenv/bin/go-pear.phar" http://pear.php.net/go-pear.phar
+	cd $HOME && ./.support/install-pear.sh && cd -
+	[ -f "$HOME/.phpenv/bin/go-pear.phar" ] && rm "$HOME/.phpenv/bin/go-pear.phar"
+
+	log_info "Installing php extensions"
+	$HOME/.phpenv/pear/bin/pecl install igbinary && (echo 'extension="igbinary.so"' >$HOME/.phpenv/versions/7.0.29/etc/conf.d/igbinary.ini)          # needed for couchbase
+	$HOME/.phpenv/pear/bin/pecl install couchbase-2.2.2 && (echo 'extension="couchbase.so"' >$HOME/.phpenv/versions/7.0.29/etc/conf.d/couchbase.ini) # their sdk has breaking changes all the time
+	# $HOME/.phpenv/pear/bin/pecl install pcntl && ( echo 'zend_extension="pcntl.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/pcntl.ini )
+	# $HOME/.phpenv/pear/bin/pecl install intl && ( echo 'zend_extension="intl.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/intl.ini ) # needed for phpstan build
+	# $HOME/.phpenv/pear/bin/pecl install memcache && ( echo 'zend_extension="memcache.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/memcache.ini ) # needed for zed
+	$HOME/.phpenv/pear/bin/pecl install memcached && (echo 'extension="memcached.so"' >$HOME/.phpenv/versions/7.0.29/etc/conf.d/memcached.ini)
+	# $HOME/.phpenv/pear/bin/pecl install mongodb && ( echo 'extension="mongodb.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/mongodb.ini )
+	# $HOME/.phpenv/pear/bin/pecl install xdebug && ( echo 'zend_extension="xdebug.so"' > $HOME/.phpenv/versions/7.0.29/etc/conf.d/xdebug.ini )
 fi
 
-if [[ ! "$(phpenv global | grep 7.2.4)" ]]; then
-    log_info "Installing php 7.2.4"
-    # phpenv install 7.2.4 && phpenv rehash
-    phpenv install 7.2.4 && php global 7.2.4 && phpenv rehash
+if [[ ! "$(phpenv versions | grep 7.2.4)" ]]; then
+	log_info "Installing php 7.2.4"
+	phpenv install 7.2.4 && phpenv rehash
+	# phpenv install 7.2.4 && php global 7.2.4 && phpenv rehash
 
-    # install pear so we can use pecl to install extensions
-    # TODO do this in a way where each php version has its own pear :/
-    # log_info "Installing pear"
-    # [ -f "$HOME/.phpenv/bin/go-pear.phar" ] || wget -O "$HOME/.phpenv/bin/go-pear.phar" http://pear.php.net/go-pear.phar
-    # cd $HOME && ./.support/install-pear.sh && cd -
-    # [ -f "$HOME/.phpenv/bin/go-pear.phar" ] && rm "$HOME/.phpenv/bin/go-pear.phar"
+	# install pear so we can use pecl to install extensions
+	# TODO do this in a way where each php version has its own pear :/
+	# log_info "Installing pear"
+	# [ -f "$HOME/.phpenv/bin/go-pear.phar" ] || wget -O "$HOME/.phpenv/bin/go-pear.phar" http://pear.php.net/go-pear.phar
+	# cd $HOME && ./.support/install-pear.sh && cd -
+	# [ -f "$HOME/.phpenv/bin/go-pear.phar" ] && rm "$HOME/.phpenv/bin/go-pear.phar"
 fi
 # }}}
 
 # install ruby version {{{
 if [[ ! "$(rbenv versions | grep 2.2.2)" ]]; then
-    log_info "Installing ruby 2.2.2"
-    rbenv install 2.2.2 # for catalog
+	log_info "Installing ruby 2.2.2"
+	rbenv install 2.2.2 # for catalog
 fi
 if [[ ! "$(rbenv version | grep 2.5.1)" ]]; then
-    log_info "Installing ruby 2.5.1"
-    rbenv install 2.5.1 && rbenv global 2.5.1 && rbenv rehash
+	log_info "Installing ruby 2.5.1"
+	rbenv install 2.5.1 && rbenv global 2.5.1 && rbenv rehash
 fi
 # }}}
 
 # install perl version {{{
 if [[ ! "$(plenv version | grep 5.27.8)" ]]; then
-    log_info "Installing perl 5.27.8"
-    plenv install 5.27.8 && plenv rehash && plenv global 5.27.8
+	log_info "Installing perl 5.27.8"
+	plenv install 5.27.8 && plenv rehash && plenv global 5.27.8
 fi
 # }}}
 
 # install python3 version {{{
 if [[ ! "$(pyenv version | grep 3.6.5)" ]]; then
-    log_info "Installing python 3.6.5"
-    pyenv install 3.6.5 && pyenv rehash && pyenv global 3.6.5
+	log_info "Installing python 3.6.5"
+	pyenv install 3.6.5 && pyenv rehash && pyenv global 3.6.5
 fi
 # }}}
 
@@ -189,53 +193,53 @@ cd -
 # update python3 pip packages {{{
 log_info "Installing/upgrading pip packages"
 pip install -r "$HOME/requirements.txt" --user
-pip-review --local --auto && \
-    pip freeze > "$HOME/requirements.txt"
+pip-review --local --auto &&
+	pip freeze >"$HOME/requirements.txt"
 # }}}
 
 # install/update composer and packages {{{
 # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
 if [[ ! "$(builtin type -p composer)" ]]; then
-    log_info "Installing composer"
-    EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
-    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-    ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+	log_info "Installing composer"
+	EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
+	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+	ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
 
-    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
-    then
-        >&2 echo 'ERROR: Invalid installer signature'
-        rm composer-setup.php
-        exit 1
-    fi
+	if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
+		echo >&2 'ERROR: Invalid installer signature'
+		rm composer-setup.php
+		exit 1
+	fi
 
-    php composer-setup.php --quiet
-    RESULT=$?
-    rm composer-setup.php
-    exit $RESULT
+	php composer-setup.php --quiet
+	RESULT=$?
+	rm composer-setup.php
+	exit $RESULT
 fi
 log_info "Installing/upgrading composer packages"
 composer global selfupdate
 composer global install
 composer global update
 if [[ ! -d $HOME/.composer/global ]]; then
-    # ^ this will install cgr. Now install cgr packages...
-    log_info "Installing cgr packages"
-    # https://github.com/consolidation/cgr
-    while read package; do
-        cgr $package
-    done <$HOME/.composer/cgr-versions.txt
+	# ^ this will install cgr. Now install cgr packages...
+	log_info "Installing cgr packages"
+	# https://github.com/consolidation/cgr
+	while read package; do
+		cgr $package
+	done <$HOME/.composer/cgr-versions.txt
 else
-    log_info "Upgrading cgr packages"
-    cgr update
+	log_info "Upgrading cgr packages"
+	cgr update
 fi
 # }}}
 
 # zplug {{{
 if [[ ! -d "$HOME/.zplug" ]]; then
-    log_info "Installing zplug"
-    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
+	log_info "Installing zplug"
+	curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
 else
-    log_info "Upgrading zplug"; cd $ZPLUG_HOME && git pull && cd -
+	log_info "Upgrading zplug"
+	cd $ZPLUG_HOME && git pull && cd -
 fi
 log_info "Installing/upgrading zplug plugins"
 $HOME/.support/install-update-zplug.zsh
@@ -254,13 +258,13 @@ tic -o "$HOME/.terminfo/78/" "$HOME/.support/screen-256color.terminfo.txt"
 
 # Mac preferences {{{
 if [[ $(defaults read com.apple.finder NewWindowTargetPath) != "file:/$HOME/" ]]; then
-    log_info "Setting finder default location"
-    defaults write com.apple.finder NewWindowTargetPath "file:/$HOME/"
+	log_info "Setting finder default location"
+	defaults write com.apple.finder NewWindowTargetPath "file:/$HOME/"
 fi
 
 if [[ $(defaults read com.apple.finder AppleShowAllFiles) != "TRUE" ]]; then
-    log_info "Setting finder to show hidden files"
-    defaults write com.apple.finder AppleShowAllFiles TRUE
-    killall Finder
+	log_info "Setting finder to show hidden files"
+	defaults write com.apple.finder AppleShowAllFiles TRUE
+	killall Finder
 fi
 # }}}
